version: "2.2"
services:
  dynamodb:
    image: "amazon/dynamodb-local"
    ports:
      - 8000:8000
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - dynamodb