version: "2.2"
services:
  dynamodb:
    image: "zestyco/dynamodb-challenge:amd" #"amazon/dynamodb-local"
    ports:
      - 8000:8000
    expose:
      - 8000
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: carmitbe1/challenge1
    ports:
      - "5000:5000"
    depends_on:
      - dynamodb